### ISSUE TITLE
看了文档,有些疑问

### ISSUE THREAD

**Issue by damu-mu** [theseustech/SotDemo#1]
当第一次正常打包后, 需要打补丁的时候.
`修改源代码，不需要clean项目`
如果clear了 是不是就无法 进行 增量的比较了? 
或者是说:打补丁之前,`clear`了 有什么影响吗? 因为 打包和打补丁之间 肯定有`时间间隔`的

**Comment by sotservice** [comment]
因为上一次的编译结果会保存到sotsaved目录下，所以clear也没关系，对比生成补丁会从这个目录里找上次的结果来对比
